apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: urlshortener-{{ .Values.env }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.backend.image }}
          command: ["celery", "-A", "worker.celery_app", "worker", "--loglevel=info"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: urlshortener-secret
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: urlshortener-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
