apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
  namespace: urlshortener-{{ .Values.env }}
data:
  REDIS_URL: "redis://redis:6379/0"
  BASE_URL: {{ .Values.baseUrl | quote }}
  APP_ENV: {{ .Values.env | quote }}
