apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: urlshortener-{{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: {{ .Values.backend.image }}
          command: ["celery", "-A", "worker.celery_app", "flower", "--port={{ .Values.flower.port }}"]
          ports:
            - containerPort: {{ .Values.flower.port }}
          envFrom:
            - configMapRef:
                name: urlshortener-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flower
  namespace: urlshortener-{{ .Values.env }}
spec:
  selector:
    app: flower
  ports:
    - port: {{ .Values.flower.port }}
      targetPort: {{ .Values.flower.port }}
