apiVersion: v1
kind: Secret
metadata:
  name: urlshortener-secret
  namespace: urlshortener-{{ .Values.env }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ "supersecret123" | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql+asyncpg://postgres:supersecret123@postgres:5432/%s" .Values.postgres.db | b64enc | quote }}
  DATABASE_URL_SYNC: {{ printf "postgresql://postgres:supersecret123@postgres:5432/%s" .Values.postgres.db | b64enc | quote }}
