name: CI/CD — URL Shortener

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag from commit SHA
        id: tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-backend:${{ steps.tag.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-frontend:${{ needs.build-backend.outputs.tag }}
          build-args: |
            NEXT_PUBLIC_API_URL=http://api.52.66.229.205.nip.io
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-helm:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Update backend image tag in values.yaml
        run: |
          sed -i "s|image: .*/urlshortener-backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-backend:${{ needs.build-backend.outputs.tag }}|" helm/urlshortener/values.yaml

      - name: Update frontend image tag in values.yaml
        run: |
          sed -i "s|image: .*/urlshortener-frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-frontend:${{ needs.build-backend.outputs.tag }}|" helm/urlshortener/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/urlshortener/values.yaml
          git commit -m "ci: deploy ${{ needs.build-backend.outputs.tag }}" || echo "No changes to commit"
          git push
